"""data migrated

Revision ID: a3fa13a68544
Revises: 
Create Date: 2026-08-06 16:12:24.960597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3fa13a68544'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Student_db',
    sa.Column('student_name', sa.String(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('student_id')
    )
    op.create_table('Teacher_db',
    sa.Column('teacher_name', sa.String(), nullable=True),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('teacher_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Teacher_db')
    op.drop_table('Student_db')
    # ### end Alembic commands ###
